var airlineNames = [
{ name: "Aegean Airlines", code: "A3" },
{ name: "Aer Lingus", code: "EI" },
{ name: "Aeroflot", code: "SU" },
{ name: "Air Algerie", code: "AH" },
{ name: "Air Astana", code: "KC" },
{ name: "Air Baltic", code: "BT" },
{ name: "Air Canada", code: "AC" },
{ name: "Air China", code: "CA" },
{ name: "Air France", code: "AF" },
{ name: "Air India", code: "AI" },
{ name: "Air India Express", code: "IX" },
{ name: "Air Mauritius", code: "MK" },
{ name: "Air New Zealand", code: "NZ" },
{ name: "Air Peace", code: "P4" },
{ name: "Airblue", code: "PA" },
{ name: "All Nippon Airways - ANA", code: "NH" },
{ name: "American Airlines", code: "AA" },
{ name: "Ariana Afghan Airlines", code: "FG" },
{ name: "Arkia Israeli Airlines", code: "IZ" },
{ name: "ASKY", code: "KP" },
{ name: "AZAL Azerbaijan Airlines", code: "J2" },
{ name: "Azimuth Airlines", code: "A4" },
{ name: "Azur Air", code: "ZF" },
{ name: "Badr Airlines", code: "J4" },
{ name: "Belavia", code: "B2" },
{ name: "Biman Bangladesh Airlines", code: "BG" },
{ name: "British Airways", code: "BA" },
{ name: "Cathay Pacific", code: "CX" },
{ name: "Cebu Pacific", code: "5J" },
{ name: "China Eastern Airlines", code: "MU" },
{ name: "China Southern Airlines", code: "CZ" },
{ name: "Czech Airlines", code: "OK" },
{ name: "Daallo Airlines", code: "D3" },
{ name: "Delta Air Lines", code: "DL" },
{ name: "Drukair", code: "KB" },
{ name: "Egyptair", code: "MS" },
{ name: "El Al Israel Airlines", code: "LY" },
{ name: "Emirates", code: "EK" },
{ name: "Enter Air", code: "OF" },
{ name: "Ethiopian Airlines", code: "ET" },
{ name: "Finnair", code: "AY" },
{ name: "FitsAir", code: "8D" },
{ name: "FlexFlight", code: "W2" },
{ name: "Fly Baghdad", code: "IF" },
{ name: "flyadeal", code: "F3" },
{ name: "flydubai", code: "FZ" },
{ name: "flynas", code: "XY" },
{ name: "Garuda Indonesia", code: "GA" },
{ name: "Go First", code: "G8" },
{ name: "Gulf Air", code: "GF" },
{ name: "Himalaya Airlines", code: "H9" },
{ name: "Iberia", code: "IB" },
{ name: "IndiGo", code: "6E" },
{ name: "Iran Air", code: "IR" },
{ name: "Iraqi Airways", code: "IA" },
{ name: "Israir", code: "6H" },
{ name: "JAL - Japan Airlines", code: "JL" },
{ name: "Jazeera Airways", code: "J9" },
{ name: "JetBlue Airways", code: "B6" },
{ name: "Jordan Aviation Airlines", code: "R5" },
{ name: "Kam Air", code: "RQ" },
{ name: "Kenya Airways", code: "KQ" },
{ name: "KLM Royal Dutch Airlines", code: "KL" },
{ name: "Korean Air", code: "KE" },
{ name: "Kuwait Airways", code: "KU" },
{ name: "LAM Mozambique Airlines", code: "TM" },
{ name: "LOT Polish Airlines", code: "LO" },
{ name: "Lufthansa", code: "LH" },
{ name: "Luxair", code: "LG" },
{ name: "Mahan Air", code: "W5" },
{ name: "Malaysia Airlines", code: "MH" },
{ name: "Middle East Airlines", code: "ME" },
{ name: "Myanmar Airways International", code: "8M" },
{ name: "Neos", code: "NO" },
{ name: "Nepal Airlines", code: "RA" },
{ name: "Nordwind Airlines", code: "N4" },
{ name: "Oman Air", code: "WY" },
{ name: "Pakistan International Airlines", code: "PK" },
{ name: "Pegasus Airlines", code: "PC" },
{ name: "Philippine Airlines", code: "PR" },
{ name: "Pobeda", code: "DP" },
{ name: "Qantas", code: "QF" },
{ name: "Qatar Airways", code: "QR" },
{ name: "Rossiya-Russian Airlines", code: "FV" },
{ name: "Royal Air Maroc", code: "AT" },
{ name: "Royal Brunei Airlines", code: "BI" },
{ name: "Royal Flight", code: "4R" },
{ name: "Royal Jordanian", code: "RJ" },
{ name: "RwandAir", code: "WB" },
{ name: "S7 Airlines", code: "S7" },
{ name: "SalamAir", code: "OV" },
{ name: "Saudia", code: "SV" },
{ name: "Serene Air", code: "ER" },
{ name: "Sichuan Airlines", code: "3U" },
{ name: "Singapore Airlines", code: "SQ" },
{ name: "SmartWings", code: "QS" },
{ name: "Somon Air", code: "SZ" },
{ name: "South African Airways", code: "SA" },
{ name: "SpiceJet", code: "SG" },
{ name: "SriLankan Airlines", code: "UL" },
{ name: "SunExpress", code: "XQ" },
{ name: "SWISS", code: "LX" },
{ name: "Syrian Air", code: "RB" },
{ name: "TAP Air Portugal", code: "TP" },
{ name: "Tarco Aviation", code: "3T" },
{ name: "Thai Airways International", code: "TG" },
{ name: "Transavia", code: "HV" },
{ name: "Tunisair", code: "TU" },
{ name: "Turkish Airlines", code: "TK" },
{ name: "Turkmenistan Airlines", code: "T5" },
{ name: "Uganda Airlines", code: "UR" },
{ name: "Ukraine International Airlines", code: "PS" },
{ name: "United Airlines", code: "UA" },
{ name: "Ural Airlines", code: "U6" },
{ name: "US-Bangla Airlines", code: "BS" },
{ name: "UTair", code: "UT" },
{ name: "Uzbekistan Airways", code: "HY" },
{ name: "Vietnam Airlines", code: "VN" },
{ name: "Vistara", code: "UK" },
{ name: "Wizz Air", code: "W6" },
{ name: "Zambia Airways", code: "ZN" },
];

$(document).ready(function() {
    var select = $("#airlineName");
    for (var i = 0; i < airlineNames.length; i++) {
        select.append($("<option>", {
            value: airlineNames[i].code,
            text: airlineNames[i].name + " (" + airlineNames[i].code + ")"
        }));
    }
    select.select2();
});